"""Character and background tables

Revision ID: 1202982b0431
Revises: e5e25d18cbd7
Create Date: 2025-02-28 11:36:23.113821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1202982b0431'
down_revision = 'e5e25d18cbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('description', sa.String(length=100000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_name'), ['name'], unique=False)

    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('description', sa.String(length=1000000), nullable=True),
    sa.Column('backstory', sa.String(length=1000000), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisme', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('background_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['background_id'], ['background.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_name'))

    op.drop_table('character')
    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_name'))

    op.drop_table('background')
    # ### end Alembic commands ###
