"""Unique constraint on background.name

Revision ID: 81d5ae96cb39
Revises: 1202982b0431
Create Date: 2025-02-28 14:54:20.834538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d5ae96cb39'
down_revision = '1202982b0431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.drop_index('ix_background_name')
        batch_op.create_index(batch_op.f('ix_background_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_name'))
        batch_op.create_index('ix_background_name', ['name'], unique=False)

    # ### end Alembic commands ###
