"""Fixed type in character.charisma

Revision ID: e70bc18b2aa9
Revises: 81d5ae96cb39
Create Date: 2025-02-28 15:10:02.855260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70bc18b2aa9'
down_revision = '81d5ae96cb39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charisma', sa.Integer(), nullable=False))
        batch_op.drop_column('charisme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charisme', sa.INTEGER(), nullable=False))
        batch_op.drop_column('charisma')

    # ### end Alembic commands ###
